FORMAT: 1A
HOST: https://not-implemented-yet/api/

# Employees Simple WebAPI

Esta é uma WebAPI simples de demonstração, para cadastro de Empregados.

## Empregados [/employees]

### Listar todos os Empregados [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "Jonathan Borges",
                "salary": 15000.99,
                "age": 30,
                "profileImage": "https://avatars1.githubusercontent.com/u/912571?s=460&u=f93fe75196ffca0d3070a571c0e592a406328678&v=4"
            }
        ]

### Obter um Empregado pelo ID [GET /employees/:id]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "Jonathan Borges",
                "salary": 15000.99,
                "age": 30,
                "profileImage": "https://avatars1.githubusercontent.com/u/912571?s=460&u=f93fe75196ffca0d3070a571c0e592a406328678&v=4"
            }
        ]
        

### Criar um novo Empregado [POST]

+ Request (application/json)

        {
            "name": "Jonathan Borges",
            "salary": 15000.99,
            "age": 30,
            "profileImage": "https://avatars1.githubusercontent.com/u/912571?s=460&u=f93fe75196ffca0d3070a571c0e592a406328678&v=4"
        }

+ Response 201 (application/json)

        {
            "id": 1,
            "name": "Jonathan Borges",
            "salary": 15000.99,
            "age": 30,
            "profileImage": "https://avatars1.githubusercontent.com/u/912571?s=460&u=f93fe75196ffca0d3070a571c0e592a406328678&v=4"
        }
        

### Atualizar um Empregado existente [PUT /employees/:id]

+ Request (application/json)

        {
            "name": "Jonathan Borges",
            "salary": 15000.99,
            "age": 30,
            "profileImage": "https://avatars1.githubusercontent.com/u/912571?s=460&u=f93fe75196ffca0d3070a571c0e592a406328678&v=4"
        }

+ Response 201 (application/json)

        {
            "id": 1,
            "name": "Jonathan Borges",
            "salary": 15000.99,
            "age": 30,
            "profileImage": "https://avatars1.githubusercontent.com/u/912571?s=460&u=f93fe75196ffca0d3070a571c0e592a406328678&v=4"
        }

        
### Excluir um Empregado [DELETE /employees/:id]

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Jonathan Borges",
            "salary": 15000.99,
            "age": 30,
            "profileImage": "https://avatars1.githubusercontent.com/u/912571?s=460&u=f93fe75196ffca0d3070a571c0e592a406328678&v=4"
        }